(() => {
  const API=(window.SANCHARAKAYA_CONFIG?.API_BASE_URL||"").replace(/\/+$/,"");
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  let chatHistory=[],lastItinerary=null,map=null,markers=[];
  const defaults={starting_location:"",days:5,group_type:"",group_size:2,language:"English",interests:[],hidden_gems:false};
  function loadJSON(k,f){try{return JSON.parse(localStorage.getItem(k)||"")||f}catch{return f}}
  function saveJSON(k,v){localStorage.setItem(k,JSON.stringify(v))}
  let memory={...defaults,...loadJSON("sancharakayaMemory",{})},savedPlaces=loadJSON("sancharakayaSavedPlaces",[]);
  function esc(v){return String(v||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
  function fmt(v){return esc(v).replace(/\*\*(.+?)\*\*/g,"<strong>$1</strong>").replace(/^### (.+)$/gm,"<strong>$1</strong>").replace(/\n/g,"<br>")}
  function initTheme(){if(localStorage.getItem("sancharakayaTheme")==="dark")document.documentElement.classList.add("dark");$("#themeBtn").onclick=()=>{document.documentElement.classList.toggle("dark");localStorage.setItem("sancharakayaTheme",document.documentElement.classList.contains("dark")?"dark":"light")}}
  function openTab(id){$$(".tab").forEach(x=>x.classList.toggle("active",x.dataset.tab===id));$$(".page").forEach(x=>x.classList.toggle("active",x.id===id));if(id==="saved")renderSaved();if(id==="explore"&&!$("#exploreGrid").children.length)explore("");if(id==="itinerary")renderItinerary(lastItinerary||loadJSON("sancharakayaItinerary",null));setTimeout(()=>map?.invalidateSize(),80)}
  function initTabs(){$$(".tab").forEach(x=>x.onclick=()=>openTab(x.dataset.tab))}
  function fillProfile(){
    $("#profileStart").value=memory.starting_location||"";$("#profileDays").value=memory.days||5;$("#profileGroup").value=memory.group_type||"";
    $("#profileGroupSize").value=memory.group_size||2;$("#profileLanguage").value=memory.language||"English";$("#profileBudget").value=memory.daily_budget_lkr||"";
    $("#profileHidden").checked=!!memory.hidden_gems;$$(".interest").forEach(x=>x.checked=(memory.interests||[]).includes(x.value));renderMemory();
  }
  function readProfile(){
    memory={...memory,starting_location:$("#profileStart").value.trim(),days:Number($("#profileDays").value||5),group_type:$("#profileGroup").value,
      group_size:Number($("#profileGroupSize").value||1),language:$("#profileLanguage").value,daily_budget_lkr:Number($("#profileBudget").value||0)||undefined,
      interests:$$(".interest:checked").map(x=>x.value),hidden_gems:$("#profileHidden").checked};
    Object.keys(memory).forEach(k=>memory[k]===undefined&&delete memory[k]);saveJSON("sancharakayaMemory",memory);renderMemory();
  }
  function bindProfile(){
    ["profileStart","profileDays","profileGroup","profileGroupSize","profileLanguage","profileBudget","profileHidden"].forEach(id=>$("#"+id).addEventListener("change",readProfile));
    $$(".interest").forEach(x=>x.addEventListener("change",readProfile));
    $("#clearMemoryBtn").onclick=()=>{memory={...defaults};chatHistory=[];saveJSON("sancharakayaMemory",memory);localStorage.removeItem("sancharakayaChat");fillProfile();$("#chatLog").innerHTML="";addMessage("bot","Memory cleared. Tell me what kind of Sri Lanka trip you want.")};
  }
  function renderMemory(){const p=[];if(memory.starting_location)p.push(`From ${memory.starting_location}`);if(memory.days)p.push(`${memory.days} days`);if(memory.group_type)p.push(memory.group_type);if(memory.daily_budget_lkr)p.push(`LKR ${Number(memory.daily_budget_lkr).toLocaleString()}/day`);if(memory.interests?.length)p.push(...memory.interests.slice(0,4));if(memory.hidden_gems)p.push("hidden gems");$("#memoryPills").innerHTML=p.map(x=>`<span>${esc(x)}</span>`).join("")}
  async function checkBackend(){const b=$("#backendBadge");try{const r=await fetch(`${API}/api/health`),d=await r.json();if(!r.ok)throw new Error();b.className=`status-badge ${d.ai_configured?"ok":"error"}`;b.textContent=d.ai_configured?`Assistant ready · ${d.knowledge_base_places} places`:"Travel tools ready"}catch{b.className="status-badge error";b.textContent="Assistant connecting"}}
  function addMessage(sender,text){const n=document.createElement("div");n.className=`msg ${sender}`;n.innerHTML=sender==="bot"?fmt(text):esc(text);$("#chatLog").appendChild(n);$("#chatLog").scrollTop=$("#chatLog").scrollHeight;return n}
  function typing(){const n=document.createElement("div");n.className="msg bot";n.id="typingMessage";n.innerHTML='<span class="typing"><i></i><i></i><i></i></span>';$("#chatLog").appendChild(n);$("#chatLog").scrollTop=$("#chatLog").scrollHeight}
  function stopTyping(){$("#typingMessage")?.remove()}
  async function sendChat(text){
    const prompt=String(text||"").trim();if(!prompt)return;readProfile();addMessage("user",prompt);chatHistory.push({role:"user",content:prompt});if(chatHistory.length>18)chatHistory=chatHistory.slice(-18);saveJSON("sancharakayaChat",chatHistory);typing();$("#sendBtn").disabled=true;
    try{
      const r=await fetch(`${API}/api/agent/chat`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({messages:chatHistory,memory})});
      const d=await r.json();if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);stopTyping();memory={...memory,...(d.memory||{})};saveJSON("sancharakayaMemory",memory);fillProfile();addMessage("bot",d.text||"No response.");chatHistory.push({role:"assistant",content:d.text||""});saveJSON("sancharakayaChat",chatHistory);renderDeck(d);
      if(d.itinerary){lastItinerary=d.itinerary;saveJSON("sancharakayaItinerary",d.itinerary)}if(d.budget)saveJSON("sancharakayaBudget",d.budget);
    }catch(e){stopTyping();const msg=String(e.message||e);const busy=/high demand|temporarily|503|unavailable/i.test(msg);const config=/AI_NOT_CONFIGURED|GEMINI_API_KEY|API key not valid|API_KEY_INVALID|not configured/i.test(msg);addMessage("bot",config?`The travel assistant is connected, but the Gemini API key needs attention. Add a valid Google AI Studio key to virtual-assistant/.env, then restart the assistant server.`:busy?`The assistant is busy right now. Please try again in a moment.`:`I couldn't complete that request right now. Details: ${msg}`)}finally{$("#sendBtn").disabled=false}
  }
  function renderDeck(d){renderWeather(d.weather||[]);renderPlaces(d.places||[],$("#placeDeck"));renderNearby(d.nearby||[]);renderActions(d.actions||[]);const pts=[];(d.places||[]).forEach(p=>p.coordinates&&pts.push(p));(d.itinerary?.plan||[]).forEach(x=>x.coordinates&&pts.push({name:x.name,coordinates:x.coordinates}));updateMap(pts)}
  function renderWeather(items){$("#weatherDeck").innerHTML=items.map(x=>`<article class="weather-card"><strong>${esc(x.place)}</strong><div class="weather-now"><div><div class="weather-temp">${x.current?.temperature_c??"—"}°C</div><small>${esc(x.current?.conditions||"")}</small></div><small>Feels ${x.current?.apparent_temperature_c??"—"}°C<br>Wind ${x.current?.wind_kmh??"—"} km/h</small></div><small>Source: Open-Meteo · 5-day forecast available</small></article>`).join("")}
  function sourceLink(p){const s=p.sources?.[0];return s?`<a class="source-link" href="${esc(s.url)}" target="_blank" rel="noopener">Source: ${esc(s.label)}</a>`:""}
  function renderPlaces(items,container){
    container.innerHTML=items.map(p=>{const image=p.image?.url?`<img class="place-image" src="${esc(p.image.url)}" alt="${esc(p.name)}" loading="lazy">`:`<div class="place-fallback">${esc(p.name.split(" ")[0])}</div>`;const mapUrl=`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(p.name+", Sri Lanka")}`;const saved=savedPlaces.some(x=>x.id===p.id);return `<article class="place-card">${image}<div class="place-body"><div class="place-meta"><span class="chip">${esc(p.region)}</span>${p.hidden_gem?'<span class="chip">Hidden gem</span>':""}<span class="chip">${esc(p.visit_duration_hours)}h</span></div><h3>${esc(p.name)}</h3><p>${esc(p.summary)}</p><p><strong>Culture:</strong> ${esc(p.heritage_culture)}</p>${sourceLink(p)}<div class="place-actions"><button data-weather="${esc(p.name)}">Weather</button><a href="${mapUrl}" target="_blank" rel="noopener">Map</a><button data-save="${esc(p.id)}">${saved?"Saved ✓":"Save"}</button></div></div></article>`}).join("");
    container.querySelectorAll("[data-weather]").forEach(b=>b.onclick=()=>sendChat(`Show me the current weather and next few days for ${b.dataset.weather}.`));
    container.querySelectorAll("[data-save]").forEach(b=>b.onclick=()=>{const p=items.find(x=>x.id===b.dataset.save);if(!p)return;toggleSave(p);b.textContent=savedPlaces.some(x=>x.id===p.id)?"Saved ✓":"Save"});
  }
  function toggleSave(p){const i=savedPlaces.findIndex(x=>x.id===p.id);i>=0?savedPlaces.splice(i,1):savedPlaces.push(p);saveJSON("sancharakayaSavedPlaces",savedPlaces)}
  function renderNearby(blocks){$("#nearbyDeck").innerHTML=blocks.map(b=>`<div class="nearby-block"><strong>${esc(b.kind||"Nearby")} near ${esc(b.place||"")}</strong><div class="nearby-list">${(b.results||[]).slice(0,8).map(x=>`<div class="nearby-item"><strong>${esc(x.name)}</strong><br><span>${esc(x.cuisine||x.kind||"")}</span></div>`).join("")||"<span>No named results returned.</span>"}</div>${b.search_url?`<a class="source-link" href="${esc(b.search_url)}" target="_blank" rel="noopener">Open live map search →</a>`:""}</div>`).join("")}
  function renderActions(actions){const btn=[];for(const a of actions){if(a.type==="train"&&a.url)btn.push(["Train schedules",a.url]);if(a.type==="ride"){if(a.uber_web_url)btn.push(["Open Uber",a.uber_web_url]);if(a.uber_app_url)btn.push(["Open Uber App",a.uber_app_url]);if(a.maps_directions_url)btn.push(["View Route",a.maps_directions_url])}if(a.type==="transport"){if(a.directions?.driving)btn.push(["Driving route",a.directions.driving]);if(a.directions?.transit)btn.push(["Transit route",a.directions.transit]);if(a.train_schedule)btn.push(["Train schedules",a.train_schedule])}}$("#actionDeck").innerHTML=btn.map(([l,u])=>`<a class="action-btn" href="${esc(u)}" target="_blank" rel="noopener">${esc(l)} →</a>`).join("")}
  function initMap(){if(!window.L)return;map=L.map("map",{zoomControl:true}).setView([7.8731,80.7718],7);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:18,attribution:"&copy; OpenStreetMap contributors"}).addTo(map)}
  function updateMap(items){if(!map||!items.length)return;markers.forEach(m=>m.remove());markers=[];const bounds=[],unique=[...new Map(items.map(x=>[`${x.coordinates.lat},${x.coordinates.lng}`,x])).values()];unique.forEach(x=>{const{lat,lng}=x.coordinates,m=L.marker([lat,lng]).addTo(map).bindPopup(`<strong>${esc(x.name)}</strong>`);markers.push(m);bounds.push([lat,lng])});bounds.length===1?map.setView(bounds[0],11):map.fitBounds(bounds,{padding:[25,25]});$("#mapEmpty").style.display="none"}
  async function explore(q){$("#exploreGrid").innerHTML='<div class="empty-state">Searching grounded destination records…</div>';try{const p=new URLSearchParams({q:q||""});if(memory.hidden_gems)p.set("hidden","true");if(memory.interests?.length)p.set("interests",memory.interests.join(","));const r=await fetch(`${API}/api/places?${p}`),d=await r.json();renderPlaces(d.matches||[],$("#exploreGrid"))}catch(e){$("#exploreGrid").innerHTML=`<div class="empty-state">Search failed: ${esc(e.message)}</div>`}}
  function renderSaved(){savedPlaces.length?renderPlaces(savedPlaces,$("#savedGrid")):$("#savedGrid").innerHTML='<div class="empty-state"><h3>No saved places</h3><p>Save destination cards from AI Guide or Explore.</p></div>'}
  function renderItinerary(plan){lastItinerary=plan||lastItinerary;const view=$("#itineraryView"),empty=$("#itineraryEmpty");if(!lastItinerary?.plan?.length){empty.classList.remove("hidden");view.innerHTML="";return}empty.classList.add("hidden");view.innerHTML=lastItinerary.plan.map(d=>`<article class="day-card"><div class="day-number">D${d.day}</div><div><h3>${esc(d.name)}</h3><p>${esc(d.region)} · ${esc(d.best_time_of_day)} · ${esc(d.suggested_visit_duration)}</p><p>${esc(d.why_it_fits)}</p><div class="day-tags">${(d.focus||[]).map(t=>`<span class="chip">${esc(t)}</span>`).join("")}</div></div><div class="day-actions"><a class="secondary-btn" target="_blank" rel="noopener" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(d.name+", Sri Lanka")}">Map</a></div></article>`).join("");updateMap(lastItinerary.plan.map(d=>({name:d.name,coordinates:d.coordinates})));renderBudget(loadJSON("sancharakayaBudget",null))}
  function renderBudget(b){const c=$("#budgetCard");if(!b?.available){c.classList.add("hidden");return}c.classList.remove("hidden");c.innerHTML=`<span class="eyebrow">USER BUDGET ENVELOPE</span><h3>LKR ${Number(b.trip_budget_envelope).toLocaleString()} total</h3><p>This allocates the budget you supplied; it is not live market pricing.</p><div class="budget-grid">${Object.entries(b.suggested_allocation||{}).map(([k,v])=>`<div><strong>${esc(k)}</strong><span>LKR ${Number(v).toLocaleString()}</span></div>`).join("")}</div>`}
  async function generatePlan(){readProfile();const ints=memory.interests?.length?memory.interests.join(", "):"a balanced mix",budget=memory.daily_budget_lkr?` My daily budget per person is LKR ${memory.daily_budget_lkr}.`:"";const p=`Build a ${memory.days||5}-day Sri Lanka itinerary starting from ${memory.starting_location||"Colombo"}. Interests: ${ints}. Group: ${memory.group_type||"traveler"} (${memory.group_size||1} people). Hidden gems: ${memory.hidden_gems?"yes":"no"}.${budget}`;openTab("guide");await sendChat(p);setTimeout(()=>openTab("itinerary"),250)}
  function shareTrip(){const trip=lastItinerary||loadJSON("sancharakayaItinerary",null);if(!trip)return alert("Generate an itinerary first.");const payload=btoa(unescape(encodeURIComponent(JSON.stringify(trip)))),url=`${location.origin}${location.pathname}#trip=${payload}`;navigator.clipboard?.writeText(url).then(()=>alert("Share link copied."))}
  function loadShared(){if(!location.hash.startsWith("#trip="))return;try{lastItinerary=JSON.parse(decodeURIComponent(escape(atob(location.hash.slice(6)))));saveJSON("sancharakayaItinerary",lastItinerary)}catch{}}
  function bindUI(){
    $("#chatForm").onsubmit=e=>{e.preventDefault();const i=$("#chatInput"),t=i.value.trim();i.value="";sendChat(t)};
    $$(".quick-prompts [data-prompt]").forEach(b=>b.onclick=()=>sendChat(b.dataset.prompt));
    $("#exploreBtn").onclick=()=>explore($("#exploreInput").value.trim());$("#exploreInput").onkeydown=e=>e.key==="Enter"&&explore(e.currentTarget.value.trim());
    $("#generatePlanBtn").onclick=generatePlan;$("#shareTripBtn").onclick=shareTrip;$("#printTripBtn").onclick=()=>window.print();
    $("#clearSavedBtn").onclick=()=>{savedPlaces=[];saveJSON("sancharakayaSavedPlaces",savedPlaces);renderSaved()};
  }
  function restoreChat(){chatHistory=loadJSON("sancharakayaChat",[]);if(chatHistory.length)chatHistory.slice(-8).forEach(x=>addMessage(x.role==="user"?"user":"bot",x.content));else addMessage("bot","Ayubowan! I’m Sancharakaya. Tell me what kind of Sri Lanka trip you want — I’ll remember your preferences and use grounded tools when I need facts or live data.")}
  function serviceWorker(){if("serviceWorker"in navigator&&location.protocol.startsWith("http"))navigator.serviceWorker.register("sw.js").catch(()=>{})}
  async function init(){initTheme();initTabs();bindProfile();fillProfile();bindUI();loadShared();restoreChat();initMap();serviceWorker();await checkBackend();setTimeout(()=>$("#preloader").classList.add("hide"),450)}
  init();
})();
